version: 1.0.{build}

branches:
  only:
    - master
shallow_clone: true
clone_depth: 1

clone_folder: c:\Build\MMapper

environment:
  matrix:
  - arch: x86
    compiler: MinGW
    QTDIR: C:\Qt\5.11\mingw53_32
    toolchain_version: 530

  - arch: x64
    compiler: VS2017
    QTDIR: C:\Qt\5.11\msvc2017_64

image: Visual Studio 2017

init:
  - set vcarch=%arch%
  - if "%arch%" == "x64" set vcarch=amd64
  - if %compiler%==VS2017 (
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %vcarch%
    ) else if not %compiler%==MinGW (
      call "C:\Program Files (x86)\Microsoft Visual Studio %toolchain_version%.0\VC\vcvarsall.bat" %vcarch%
    )
  - if %compiler%==MinGW (
      set CMAKE_GENERATOR="MinGW Makefiles"
    ) else (
      set CMAKE_GENERATOR="NMake Makefiles"
    )
  - git config --global core.autocrlf input
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - echo QTDIR=%QTDIR%
  - echo CMAKE_GENERATOR=%CMAKE_GENERATOR%

install:
  - ps: $env:package_version = (Get-Content -Raw -Path MMAPPER_VERSION).trim()
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"

before_build:
  - set PATH=%QTDIR%\bin;%PATH%
  - if %compiler%==MinGW set PATH=C:\Qt\Tools\mingw%toolchain_version%_32\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - echo PATH=%PATH%
 
build:

build_script:
  - cd c:\Build\MMapper
  - md winbuild
  - cd winbuild
  - cmake .. -G %CMAKE_GENERATOR% "-DCMAKE_PREFIX_PATH=%QTDIR%"
  - cmake --build . -j %NUMBER_OF_PROCESSORS%
  - cpack

test_script:
  - cmd: ctest -V

artifacts:
  - path: winbuild\mmapper-$(package_version)-Windows-$(arch).exe
    name: MMapper Installer
  
  - path: winbuild\mmapper-$(package_version)-Windows-$(arch).zip
    name: MMapper ZIP
