name: mmapper
version: 2.5.1+git
version-script: git describe --tags --always --long
icon: src/resources/icons/m.png
summary: MUME Mapper
description: |
  MMapper is a graphical mapper for a MUD named MUME (Multi-Users in Middle
  Earth). The game is traditionally played in a text-only mode, but MMapper tries
  to represent the virtual world in user-friendly graphical environment. It acts
  as a proxy between a telnet client and a MUD server, being able to analyze game
  data in real time and show player's position in a map.

grade: stable
confinement: strict

apps:
  mmapper-desktop:
    command: desktop-launch mmapper
    desktop: usr/share/applications/mmapper.desktop
    plugs:
      - home
      - network
      - network-bind
      - opengl
      - x11
      - gsettings

parts:
  mmapper:
    plugin: cmake
    source: .
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - build-essential
      - zlib1g-dev
      - libssl-dev
      - libqt5opengl5-dev
      - qttools5-dev-tools
    stage-packages:
      - zlib1g
      - libssl1.0.0
      - libc6
      - libqt5xml5
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=mmapper|Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/mmapper.png|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/mmapper.desktop
    after:
      - desktop-qt5
