language: cpp

dist: xenial

# https://docs.travis-ci.com/user/languages/cpp/
matrix:
  include:
    #
    # Mac
    #
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      addons:
        homebrew:
          packages:
            - cmake
            - qt5
            - clang-format
            - miniupnpc
            - lcov
            - openssl
      env:
        - MATRIX_EVAL=""
        - CLANG_FORMAT=clang-format
    #
    # Linux GCC 7
    #
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
            - sourceline: 'ppa:beineri/opt-qt597-xenial'
          packages:
            - g++-7
            - clang-format-6.0
            - cmake
            - libminiupnpc-dev
            - lcov
            - qt59base
            - mesa-common-dev
      env:
        - QT=59 MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CLANG_FORMAT=clang-format-6.0
    #
    # Linux GCC 8
    #
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
            - sourceline: 'ppa:beineri/opt-qt597-xenial'
          packages:
            - g++-8
            - clang-format-6.0
            - cmake
            - libminiupnpc-dev
            - lcov
            - qt59base
            - mesa-common-dev
      env:
        - QT=59 MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - CLANG_FORMAT=clang-format-6.0

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt5'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export PATH=/usr/local/opt/qt5/bin:$PATH'
  - qmake -v

before_script:
  # Linux
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[ "$TRAVIS_OS_NAME" != linux ] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[ "$TRAVIS_OS_NAME" != linux ] || export QT_SELECT=qt5'
  # Mac
  - '[[ "$TRAVIS_OS_NAME" != osx || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export MMAPPER_CMAKE_EXTRA=-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl'
  # Code style check
  - $CLANG_FORMAT -version
  - find . -type f -name *.cpp -o -name *.h -exec $CLANG_FORMAT -style=file -i {} \;
  - |
    if  [[ -n $(git diff) ]]; then
      echo
      git diff
      echo
      echo "Please fix your code style:"
      echo "find . -type f -name *.cpp -o -name *.h -exec clang-format -i -style=file {} \;"
      [[ $(git diff --stat | wc -l) -lt 5 ]] || exit -1
    fi
  # Prepare Makefile
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. $MMAPPER_CMAKE_EXTRA -DUSE_CODE_COVERAGE=true

script:
  - make -j2

after_success:
  - lcov  --zerocounters  --directory .
  - ctest -V
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --directory . --capture --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  - cpack
