language: cpp

dist: trusty

# https://docs.travis-ci.com/user/languages/cpp/
matrix:
  include:
    #
    # Mac
    #
    - os: osx
      compiler: clang
      env:
        - MATRIX_EVAL="brew update"
    #
    # Linux GCC 4
    #
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-4.9
            - clang-format-6.0
      env:
        - QT=59 PPA=beineri/opt-qt595-trusty MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    #
    # Linux GCC 5
    #
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-5
            - clang-format-6.0
      env:
        - QT=59 PPA=beineri/opt-qt595-trusty MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    #
    # Linux GCC 6
    #
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-6
            - clang-format-6.0
      env:
        - QT=59 PPA=beineri/opt-qt595-trusty MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    #
    # Linux GCC 7
    #
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-7
            - clang-format-6.0
      env:
        - QT=59 PPA=beineri/opt-qt595-trusty MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    #
    # Linux GCC 8
    #
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-8
            - clang-format-6.0
      env:
        - QT=59 PPA=beineri/opt-qt595-trusty MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"
  - '[[ "$TRAVIS_OS_NAME" != linux || -z "$PPA" ]] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install cmake'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || sudo apt-get -qy install qt${QT}base qt${QT}xmlpatterns'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt5 clang-format openssl'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt5'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export PATH=/usr/local/opt/qt5/bin:$PATH'
  - qmake -v

before_script:
  # Linux
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  # Mac
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export MMAPPER_CMAKE_EXTRA=-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl'
  # Code style check
  - clang-format -version
  - find . -type f -name *.cpp -o -name *.h -exec clang-format -style=file -i {} \;
  - |
    if  [[ -n $(git diff) ]]; then
      echo
      git diff
      echo
      echo "Please fix your code style:"
      echo "find . -type f -name *.cpp -o -name *.h -exec clang-format -i -style=file {} \;"
      exit -1
    fi
  # Prepare Makefile
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. $MMAPPER_CMAKE_EXTRA

script:
  - make -j2

after_success:
  - ctest -V
  - cpack
