language: cpp

dist: trusty

# https://docs.travis-ci.com/user/languages/cpp/
matrix:
  include:
    - os: osx
      compiler: clang
      env:
        - MATRIX_EVAL="brew update"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - QT=59 PPA=beineri/opt-qt591-trusty MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - QT=59 PPA=beineri/opt-qt591-trusty MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - QT=59 PPA=beineri/opt-qt591-trusty MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - QT=59 PPA=beineri/opt-qt591-trusty MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - '[[ "$TRAVIS_OS_NAME" != linux || -z "$PPA" ]] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install cmake'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || sudo apt-get -qy install qt${QT}base qt${QT}xmlpatterns'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt5'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt5'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export PATH=/usr/local/opt/qt5/bin:$PATH'
  - qmake -v

before_script:
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script:
  - make -j2
  - ctest -V

